### ISSUE TITLE
Problem: it's not clear how to troubleshoot Compose when out of memory

### ISSUE THREAD

**Issue by ross-spencer** [artefactual-labs/am#10]
This might be a difficult one to re-create but it has also happened to me fairly consistently today. Managed to see this three times with the same conditions. Only observed where we managed to get up to once (other Windows open when it stalled previously).

Following the steps [here](https://github.com/artefactual-labs/am/tree/master/compose)

Ran:

     $ docker-compose up -d --build

Running Vagrant install at the same time, once the last step completes, my Ubuntu machine would progressively slow down until stalling. 

Final time I tried this I managed to capture a dmesg which shows some activity, but I'm not sure if this will be useful enough on its own. 

![17 10-stalling](https://user-images.githubusercontent.com/1880412/32706310-89234724-c881-11e7-803c-8a7af4921472.jpg)

Could only resolve by force-restarting my machine. 

Tried: 

     $ docker-compose up -d --force-recreate --build 

No discernible impact.

**Comment by sevein** [comment]
Sounds like you're running out of memory.

**Comment by ross-spencer** [comment]
Will try and repeat with swap now enabled! :)

**Comment by ross-spencer** [comment]
It looks like it too ;) 

![image](https://user-images.githubusercontent.com/1880412/32756682-42ba66e0-c940-11e7-9d82-9be7a8982c9b.png)

Okay, that was easier to test than anticipated. Docker AM was already running and so I just asked Vagrant to start. Pretty much all my spare memory gone. 

Before we close this issue out, do you or @sromkey, @sallain think we should put a hint on the [quick start guide](https://github.com/artefactual-labs/am-packbuild/blob/master/packer/templates/vagrant-box-archivematica/Vagrantfile) saying if there are any problems with a machine becoming unresponsive to change the setting in the file you referenced earlier: https://www.archivematica.org/en/docs/archivematica-1.6/getting-started/quick-start/quick-start/#quick-start-install and then:

     vagrant reload

Or maybe nuance the requirements in the quick-start to say the virtual machine will use 4GB, so you need spare on top of that?

**Comment by sevein** [comment]
We should add a note in https://github.com/artefactual-labs/am/tree/master/compose#troubleshooting about this issue (out of memory) because it may come up again.

**Comment by sevein** [comment]
I've added some notes to the troubleshooting guide in this commit: dce21c9, e.g. check system requirements, suggested to find more information in issue trackers, etc...
