### ISSUE TITLE
Rebuild Index

### ISSUE THREAD

**Issue by rodyoukai** [artefactual-labs/am#100]
Hi,

I have troubles with my container and I be forced to rebuild them, My AIPS still there, How can I Rebuild index to see my AIPs in dashboard and Storage service?

**Comment by sevein** [comment]
Hola Rodrigo!

There are a couple of commands that can help you. They're described in our docs, see https://www.archivematica.org/en/docs/archivematica-1.12/admin-manual/maintenance/maintenance/#rebuild-the-indexes. When using containers, you can try running commands as follows:

    make manage-dashboard ARG="rebuild_aip_index_from_storage_service"

Remember, artefactual-labs/am is not a production-grade environment!

**Comment by sevein** [comment]
I'm closing the issue but feel free to post more comments.

**Comment by rodyoukai** [comment]
Thanks @sevein 

When I run that command I get: 

Unknown command: 'rebuild_aip_index_from_storage_service'
Type 'manage.py help' for usage.
ERROR: 1
Makefile:65: recipe for target 'manage-dashboard' failed
make: *** [manage-dashboard] Error 1

**Comment by sevein** [comment]
You must be using an old version of the code. Make sure you check out qa/1.x in src/archivematica and qa/0.x in src/archivematica-storage-service. Change dirs from your terminal, check out the branches and then pull.
Alternatively, where you were running `submodule update --init --recursive` try the following instead: `git submodules update --recursive --remote` which forces git to use the remote-tracking branch as opposed to the recorded commit in artefactual-labs/am.
