### ISSUE TITLE
Problem: can't run acceptance tests

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/am#2]
The ansible role offers the ability to run the [acceptance tests](https://github.com/artefactual-labs/archivematica-acceptance-tests) in the same host where AM is deployed. In theory, it should be possible to do the same in the Compose environment that this repo hosts.

What would it take?

##### DOWNLOAD THE SOURCES

Add the following task to the `playbooks/inc/repos-1.7.yml` playbook:

```
- name: "Archivematica Acceptance Tests repository"
  repo: "https://github.com/artefactual-labs/archivematica-acceptance-tests"
  version: "master"
  dirname: "archivematica-acceptance-tests"
```

##### ADD SERVICE TO DOCKER-COMPOSE.YML

```
archivematica-acceptance-tests:
  build:
    context: "../src/archivematica-acceptance-tests"
  links:
    - "nginx"
  volumes:
    - ... (what's needed?)
```

See also the comment below above a possible `docker-compose.test.yml` file.

##### ADD SCRIPT TO RUN THE TESTS

Something similar to the following could work:

```
#!/usr/bin/env bash

docker-compose run \
	--rm \
	--entrypoint behave \
		archivematica-acceptance-tests --
			-D am_username=test \
			-D am_password=test \
			-D am_url=http://nginx:80/ \
			-D am_version=1.7 \
			-D am_api_key=test \
			-D ss_username=test \
			-D ss_password=test \
			-D ss_url=http://nginx:8000/ \
			-D ss_api_key=test \
			-D transfer_source_path='/src/archivematica-sampledata/TestTransfers/acceptance-tests' \
			-D home=root \
			-D driver_name=Chrome \
			-D ssh_accessible=no
```

##### EXECUTION ENVIRONMENT

I think that we need to add a `Dockerfile` to the `archivematica-acceptance-tests` repository that builds an environment when we can run the test suite. This can get tricky because the standard procedure is to install a VNC server which is executed in the background. Once it's started, the user runs `behave` and WebDriver will use the display port assigned.

An alternative is to create a `docker-compose.test.yml` with a few extra services in addition to what's already in `docker-compose.yml`. SeleniumHQ shares [an example](https://github.com/SeleniumHQ/docker-selenium/wiki/Getting-Started-with-Docker-Compose) in their wiki where they use `selenium/hub` as some kind of test dispatcher. The AM acceptance test could communicate directly with `selenium/hub`.

The new `google-chrome --headless` is also interesting, but it's an approach limited to Chrome. It's elegant and efficient but it does not seem to be available in other browsers, e.g. see this [Firebox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1338004).

**Comment by sevein** [comment]
I wrote a Dockerfile to run do some tests. It's here: https://gist.github.com/sevein/e952510b5582e58dd4be7b1742695202 - for future reference.

**Comment by jrwdunham** [comment]
Hey sevein, Justin just found this article about headless Firefox so I'm linking it here in case it's useful and you haven't come across it yet: https://developer.mozilla.org/en-US/Firefox/Headless_mode.

**Comment by sevein** [comment]
@mamedin mentioned today that he found the headless mode to be much easier to set up when using Compose. So we have Firefox and Chrome headless now, I think we don't need VNC anymore?

**Comment by sevein** [comment]
If we use Travis CI at some point it seems that we can also use the free service provided by Sauce Labs as the browser testing platform.

See:
- https://docs.travis-ci.com/user/sauce-connect/
- https://github.com/saucelabs-sample-test-frameworks/Python-Behave-Selenium

**Comment by jrwdunham** [comment]
This sounds very cool. I don't think that it is possible for the acceptance tests to successfully run in parallel against the same Archivematica instance. If true, I think either we would have to change that (hard) or (easier) we would have to spin up one AM/SS instance for each process `P` in `behave --processes P --parallel-element scenario`.

**Comment by sevein** [comment]
Right! Probably easier to run them sequentially. But we could also ru spin up two different projects with Compose, e.g.:

$ docker-compose --project-name P1 --file docker-compose.acceptance-tests.yml up -d
$ docker-compose --project-name P2 --file docker-compose.acceptance-tests.yml up -d

It wouldn't work right now because we're mapping to static ports, but I think that'd be the only issue.
