### ISSUE TITLE
Problem: we can't defer tasks in SS

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/am#21]
This is a known problem that we want to address before the 1.0 release of SS. Typically you'd use a distributed task queue and there are solutions like Gearman (which we already use in AM) or Celery + broker. We've talked about adding new async endpoints to the SS API to avoid backward-incompatible changes and a bunch of other ideas.

I was reminded about this issue by another problem I'm trying to solve: https://github.com/artefactual/archivematica-storage-service/issues/269. I want to submit a task that deletes a temporary directory created by SS but I can't effectively do that (ignore workarounds) without postponing the work. See more details here: https://github.com/artefactual/archivematica-storage-service/issues/269.

**Comment by jhsimpson** [comment]
Since this issue was filed, asynchronous processing was added to the storage service, starting here: https://github.com/artefactual/archivematica-storage-service/pull/327

I'm closing this issue as a result.
