### ISSUE TITLE
Problem: test-mcp-client target fails

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/am#28]
I was pretty sure that I had already filed this issue but maybe not? When you run `make test-mcp-client` in Compose the tests don't pass however it does pass in Travis CI our outside container. There are other issues related to testing in general that may be related, see: https://github.com/artefactual-labs/am/issues?q=is%3Aissue+is%3Aopen+label%3Adev.

**Comment by ross-spencer** [comment]
@sevein I run up against this issue most when cherry-picking into `stable/1.7.x` because we're not doing it from a branch, there isn't the luxury to push and see what Travis online says. Is there a workaround? Should we investigate a workflow for running Travic CI locally? (cc. @jrwdunham)

**Comment by ross-spencer** [comment]
This may have been the wrong path to head down today, but I have been trying a combination of these posts to see what a 'local' Travis CI would look like:

* https://gist.github.com/MichaReiser/3874e278eb0d9d839ddc752df8a7662c
* https://medium.com/google-developers/how-to-run-travisci-locally-on-docker-822fc6b2db2e
* https://github.com/travis-ci/travis-build

The thesis I think being to have a standard docker test image that we could use to make sure our environments were consistent with the server (which I guess has both advantages and disadvantages). 

There are various inaccuracies with each of these posts above so it took me some time to get anywhere. i think i need to park it for now, but interested in the continuing conversation.

**Comment by sevein** [comment]
I think the problem is that for a long time we've always assumed that the tests were going to be executed like the following:

    $ git clone https://github.com/artefactual/archivematica
    $ cd archivematica
    $ tox -e py27
    179 passed, 10 skipped, 2 xfailed in 62.61 seconds

That's what Travis CI does. You could do the same and it should work. So I guess that's why this issue can't be considered a blocker.

But like you I always thought that we should run the tests in a predefined environment (and not whatever Travis thinks it should be or you may have on your machine). Because we already have Docker images defining the environment we want, `make test-mcp-client` or `make test-dashboad` are attempts to run the tests inside these environments. The latter works and we need to see what's wrong with the former. I think it's close but we need to figure out the remaining tweaks. E.g. when you run `make test-mcp-client` we're really doing the following:

```
docker-compose run --workdir /src/MCPClient --rm --user=root --entrypoint=py.test archivematica-mcp-client
```

So there are three test files that don't like that. If you ignore them then it works:

```
docker-compose run --workdir /src/MCPClient --rm --user=root --entrypoint=py.test archivematica-mcp-client --ignore=tests/test_rights_from_csv.py --ignore=tests/test_reingest_mets.py --ignore=tests/test_create_aip_mets.py

requirements/test.txt s
tests/test_antivirus.py ...........
tests/test_antivirus_clamdscan.py ....
tests/test_antivirus_clamscan.py ......
tests/test_dip_generation_helper.py ....
tests/test_email_fail_report.py ..
tests/test_json_conversion.py ....
tests/test_parse_mets_to_db.py ...............
tests/test_post_store_aip_hook.py ...
tests/test_sanitize.py .
tests/test_store_file_modification.py .

======== 51 passed, 1 skipped in 85.20 seconds ===
```

So I think that we need to figure out what's wrong with `tests/test_rights_from_csv.py`, `tests/test_reingest_mets.py` and `tests/test_create_aip_mets.py`. I much suspect the problem is that they're not totally self-contained, they must be relying on some database state leftovers from previous tests that we're not executing anymore like when we do the global `tox`.

So once we solve this issue I think that your idea of "standard docker test image" would become a reality as long as you're willing to consider `MCPClient.Dockerfile` that image which is what `make test-mcp-client` attempts.

Promoting this way of running the tests to CI would also be required/ideal. Travis could do that for us (see https://docs.travis-ci.com/user/docker/). However I think that we could just leave Travis doing it the old way at least for a while and have something in addition like CircleCI (see example https://github.com/CircleCI-Public/circleci-demo-python-flask) primarily designed to run your tests on an image of our choice.

Perhaps as part of the AM18 cycle we can put some more thought on this. A common practice seems to be to build the images and push them to a registry as soon as commits happen. Then you use those images to run all your tests (and if passes) make a deployment and run acceptance tests (and if passes) upgrade qa sites etc etc...

**Comment by sevein** [comment]
FYI we could have as many CI integrations as we want, e.g. check out this screenshot:

![image](https://user-images.githubusercontent.com/606459/37556970-cf76f60e-29ba-11e8-9c1b-029db0afee13.png)

**Comment by sevein** [comment]
@ross-spencer take a look at my quick fix here: https://github.com/artefactual/archivematica/commit/d9f8daa379e6794a05f58a8cd52b007835c38871. I'm not sure if I understand the root cause, it'd be nice to figure it out.

A nice way to run the tests for a trial and error kind of workflow is:

    docker-compose run --no-deps --workdir /src/MCPClient --rm --user=root --entrypoint=py.test archivematica-mcp-client --reuse-db --exitfirst

It takes only 13 seconds on each run because it re-uses the database.
