### ISSUE TITLE
Problem: /tmp/ locations used in docker deployments are volatile

### ISSUE THREAD

**Issue by ross-spencer** [artefactual-labs/am#34]
Archivematica Docker deployments reference two `/tmp/` locations for shared volumes accessible to the containers. 

- `/tmp/am-pipeline-data`
- `/tmp/ss-location-data`

Both locations are known to be volatile and so the user can often lose these locations when the host machine is restarted.

It could be beneficial to users to have guidance (potential ideas) on:

- Minimal steps to re-establish the Archivematica environment upon restart
- Guidance on setting up alternative locations when setting up the Docker environment

**Comment by sevein** [comment]
We're now using `$(HOME)/.am`.
