### ISSUE TITLE
Problem: readme doesn't specify minimum hardware specs required

### ISSUE THREAD

**Issue by jhsimpson** [artefactual-labs/am#41]
The playbooks in the compose directory create at least 11 containers.  The readme doesn't say what the minimum memory or cpu or disk space requirements for the host machine need to be for that set of containers to startup and and run properly.  Are the hardware requirements the same for non-docker based distributions of Archivematica?

**Comment by sevein** [comment]
Fixed by 1db46b27c798f1b21046db61175d5a7a090dd2a2.
