### ISSUE TITLE
Problem: GPG feature may not work with Linux host

### ISSUE THREAD

**Issue by jrwdunham** [artefactual-labs/am#46]
The GPG feature was tested using an AM docker deploy (am.git/compose/) of AM 1.7 (rc3) (SS 0.11) on a Linux host and failed. The same test passed on a Mac OS host. The GPG feature was tested by running the [AIP Encryption acceptance tests](https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/66/files). 

The particular failure was Ajax calls to `get_form_type/` were hanging when the Access protocol was changed to "GPG encryption on Local Filesystem" in the  /spaces/create/ form. Initially, requests were timing out. Then, after mounting /dev/urandom to container /dev/random, 500 errors were triggered by `AttributeError/TypeError`s arising from `None` being returned as system GPG key (cf. gpgutils).

The culprit may not be the host OS, but instead the lack of noise (randomness) in a development machine with fewer active processes (fewer applications running).

More investigation needed.

**Comment by sevein** [comment]
Replaced by https://github.com/archivematica/Issues/issues/225.
