### ISSUE TITLE
Problem: compose build fails with webpack not found

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/am#49]
@cdekok and @ablwr reported the same issue.

This is the Dashboard container:

```
sh: 1: webpack: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! transfer-browse@0.0.0 prepublish: `webpack --progress --colors --entry ./app.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the transfer-browse@0.0.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-16T10_03_57_466Z-debug.log```
```

**Comment by ablwr** [comment]
For the wider world, I'll note that I'm on macOS Sierra, docker-compose v1.18, docker v17.12.

**Comment by sevein** [comment]
And FWIW, it's working for me!

![image](https://user-images.githubusercontent.com/606459/37732452-456b33b2-2d02-11e8-874b-37db835dee03.png)

Radda found this issue too in a different environment so this is likely not because of Compose. See https://github.com/artefactual/deploy-pub/issues/56. @jraddaoui is looking into it.

**Comment by sevein** [comment]
Thanks for checking it out! We should consider yarn because it definitely seems less problematic I totally agree. Also, we should merge transfer-browser and appraisal-tab into a single app - they're now separate because they came from different repos. Also it wouldn't hurt to update our frontend libraries in particular webpack, we're using an ancient version!

**Comment by nkrabben** [comment]
Is switching to yarn something I could do locally by editing the Makefile or similiar? I'm running into the same webpack error on macOS 10.13.

**Comment by sevein** [comment]
Totally @nkrabben! During the image build things happen here:

https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard.Dockerfile#L43-L49
```
COPY dashboard/frontend/transfer-browser/ /src/dashboard/frontend/transfer-browser/
RUN chown -R archivematica:archivematica /src/dashboard/frontend/transfer-browser \
	&& su -l archivematica -c "cd /src/dashboard/frontend/transfer-browser && npm install"

COPY dashboard/frontend/appraisal-tab/ /src/dashboard/frontend/appraisal-tab/
RUN chown -R archivematica:archivematica /src/dashboard/frontend/appraisal-tab \
	&& su -l archivematica -c "cd /src/dashboard/frontend/appraisal-tab && npm install"
```

The `Makefile` in this repo also build the frontend assets for us to make it available in the working trees on your host that we're injecting as volumes into the containers. It happens here:

https://github.com/artefactual-labs/am/blob/4c09a467ec1a6dd5b3342d57dffab1bb60fa5263/compose/Makefile#L78-L90

You may notice that we have two frontend apps, appraisal-tab and transfer-browser. It's totally unnecessary, it's like that because they used to live in different repos. I'm hoping in AM18 we can merge them and take that opportunity to update webpack.

**Comment by helrond** [comment]
I'm also experiencing this error during the build process when running `docker-compose up -d --build`.

In addition to the error messages noted by @ablwr above, I also saw the following:
```
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
```

Changing the `prepublish` key on line 29 of am/src/archivematica/src/dashboard/frontend/transfer-browser/package.json to `prepublishOnly` resolved the issue during build.

**Comment by ablwr** [comment]
To get around this, @sevein recommended I build the individual bootstrap frontend requirements locally, and I updated the `compose` docs to reflect that! Still just a patch, but I was able to make progress. I also then switched to a Linux machine but I look forward to debugging this issue in the future. ;) 

https://github.com/artefactual-labs/am/tree/master/compose#make-bootstrap-fails-to-run

**Comment by jrwdunham** [comment]
I was able to make this work with the naive changes in this WIP PR: https://github.com/artefactual-labs/am/pull/70 (macOS Sierra v10.13.5, docker-compose v1.21, docker v18.03.

**Comment by sevein** [comment]
Replaced by https://github.com/archivematica/Issues/issues/226.
