### ISSUE TITLE
Problem: Add json_links to makefile

### ISSUE THREAD

**Issue by ross-spencer** [artefactual-labs/am#50]
Thanks to recent changes from @sevein and @jrwdunham we can export a list of json_links using the following command:

`$ sudo docker-compose exec archivematica-dashboard /src/dashboard/src/manage.py json_links`

We can then export somewhere using the docker command:

`$ docker cp <container-id>:/var/archivematica/sharedDirectory/tmp/json-links-6gGucN.json exported_links.json`

I'm not sure what the compose equivalent is yet. 

This ticket suggests adding the capability to the `makefile` and exporting to the `am/compose` directory.

**Comment by sevein** [comment]
> docker cp <container-id>:/var/archivematica/sharedDirectory/tmp/json-links-6gGucN.json exported_links.json

An alternative is to used the external volume already available in Compose, e.g. `/tmp/am-pipeline-data/tmp/json-links-6gGucN.json`.

> This ticket suggests adding the capability to the makefile and exporting to the am/compose directory.

I think that this is a good idea but because the list of management commands keep growing I think that we need to find an unified method to saves us some work. Maybe something like the following:

```Makefile
dashboard-manage:
    	docker-compose run --rm --entrypoint /src/dashboard/src/manage.py archivematica-dashboard ${ARGS}

storage-service-manage:
    	docker-compose run --rm --entrypoint /src/storage_service/manage.py archivematica-storage-service ${ARGS}
```

So we can run commands like:

    make dashboard-manage ARGS="--help"
    make dashboard-manage ARGS="json_links --help"
    # etc...

**Comment by sevein** [comment]
Joel Dunham implemented the solution suggested above:

```
$ make help | grep manage
manage-dashboard               Run Django /manage.py on Dashbaord, suppling <command> [options] as value to ARG, e.g., `make manage-ss ARG=shell`
manage-ss                      Run Django /manage.py on Storage Service, suppling <command> [options] as value to ARG, e.g., `make manage-ss ARG='shell --help'`
```
