### ISSUE TITLE
Building archivematica-mcp-server

### ISSUE THREAD

**Issue by rodyoukai** [artefactual-labs/am#72]
I'm try to install my development enviroment with docker, I follow the README.md but in this command:

`docker-compose up -d --build`

I get: 

> Running
> 
>  in cba0e422b7c5
> + apt-get update
> Err http://security.debian.org jessie/updates InRelease
>   
> Err http://deb.debian.org jessie InRelease
>   
> Err http://deb.debian.org jessie-updates InRelease
>   
> Err http://security.debian.org jessie/updates Release.gpg
>   Temporary failure resolving 'security.debian.org'
> Err http://deb.debian.org jessie Release.gpg
>   Temporary failure resolving 'deb.debian.org'
> Err http://deb.debian.org jessie-updates Release.gpg
>   Temporary failure resolving 'deb.debian.org'
> Reading package lists...
> W: Failed to fetch http://deb.debian.org/debian/dists/jessie/InRelease  
> 
> W: Failed to fetch http://security.debian.org/debian-security/dists/jessie/updates/InRelease  
> 
> W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  
> 
> W: Failed to fetch http://security.debian.org/debian-security/dists/jessie/updates/Release.gpg  Temporary failure resolving 'security.debian.org'
> 
> W: Failed to fetch http://deb.debian.org/debian/dists/jessie/Release.gpg  Temporary failure resolving 'deb.debian.org'
> 
> W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/Release.gpg  Temporary failure resolving 'deb.debian.org'
> 
> W: Some index files failed to download. They have been ignored, or old ones used instead.
> + apt-get install -y --no-install-recommends gettext libmysqlclient-dev libldap2-dev libsasl2-dev locales locales-all
> Reading package lists...
> Building dependency tree...
> Reading state information...
> Package locales is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> Package locales-all is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> Package gettext is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> Package libldap2-dev is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'gettext' has no installation candidate
> E: Package 'libldap2-dev' has no installation candidate
> E: Unable to locate package libsasl2-dev
> E: Package 'locales' has no installation candidate
> E: Package 'locales-all' has no installation candidate
> ERROR: Service 'archivematica-mcp-server' failed to build: The command '/bin/sh -c set -ex 	&& apt-

> get update 	&& apt-get install -y --no-install-recommends 		gettext 		libmysqlclient-dev 		libldap2-dev 		libsasl2-dev 		locales 		locales-all 	&& rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
 
How can I solved, I am new in docker :(

**Comment by sevein** [comment]
Hi @rodyoukai! 👋
That seems to be a problem with the DNS resolver, see the bits that read `Temporary failure resolving`. Not sure why hostnames like `deb.debian.org` can't be resolved in your environment but they should be.

**Comment by rodyoukai** [comment]
Thanks!! You right, I need set up my own DNS In Dockers...
