### ISSUE TITLE
Can't start transfer - browse doesn't list the location's folders

### ISSUE THREAD

**Issue by kurokijr** [artefactual-labs/am#78]
I'm new to archivematica and tried to install a little lab on my computer. Get through the installations steps without problems but when I started to use it, got this error message on dashboard log:

archivematica-dashboard_1        | ERROR     2019-04-01 20:32:56  django.request:base:handle_uncaught_exception:256:  Internal Server Error: /filesystem/children/location/a71dbfc2-5479-4fd0-a40b-bf1f3250da2f/
archivematica-dashboard_1        | Traceback (most recent call last):
archivematica-dashboard_1        |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
archivematica-dashboard_1        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
archivematica-dashboard_1        |   File "/src/dashboard/src/components/filesystem_ajax/views.py", line 123, in directory_children_proxy_to_storage_server
archivematica-dashboard_1        |     response = storage_service.browse_location(location_uuid, path)
archivematica-dashboard_1        |   File "/src/archivematicaCommon/lib/storageService.py", line 211, in browse_location
archivematica-dashboard_1        |     response = _storage_api_session().get(url, params=params)
archivematica-dashboard_1        |   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
archivematica-dashboard_1        |     return self.request('GET', url, **kwargs)
archivematica-dashboard_1        |   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
archivematica-dashboard_1        |     resp = self.send(prep, **send_kwargs)
archivematica-dashboard_1        |   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
archivematica-dashboard_1        |     r = adapter.send(request, **kwargs)
archivematica-dashboard_1        |   File "/src/archivematicaCommon/lib/storageService.py", line 71, in send
archivematica-dashboard_1        |     return super(HTTPAdapterWithTimeout, self).send(*args, **kwargs)
archivematica-dashboard_1        |   File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 529, in send
archivematica-dashboard_1        |     raise ReadTimeout(e, request=request)
archivematica-dashboard_1        | ReadTimeout: HTTPConnectionPool(host='archivematica-storage-service', port=8000): Read timed out. (read timeout=5.0)

I can't find the file /usr/local/lib/python2.7/site-packages/requests/adapters.py either to try to manually reset the timeout value.

has anyone gotten though this?

**Comment by sevein** [comment]
I've seen that happened in very slow environments where SS couldn't manage to generate a respond within 5 seconds. Two things that you could try:

1. Increase the timeout via envs:
`ARCHIVEMATICA_DASHBOARD_STORAGE_SERVICE_CLIENT_QUICK_TIMEOUT` (in `archivematica-dashboard` service)
`ARCHIVEMATICA_MCPCLIENT_STORAGE_SERVICE_CLIENT_QUICK_TIMEOUT` (in `archivematica-mcpclient` service)

2. Disable object counting in SS
- Open http://127.0.0.1:62081/administration/
- Check "Object counting in spaces is disabled?"
- Save

Let us know how it goes, feel free to open this issue if the problem persists!
